author = "ycwang"
baseURL = "https://www.ycwang.me/"
languageCode = "zh-cn"
copyright = "Copyright © 2020–2021, ycwang all rights reserved."
paginate = 8
title = "Yongcong Wang"
theme = "alageek"

[params]
copyright = "© 2021 by ycwang"
copyrightUrl = "https://www.ycwang.me"
description = "Portfolio"
faviconfile = "/img/favicon.ico"
latestpostcount = 8
logofile = "/img/logo.png"
highlightjs = true
highlightjslanguages = [ "bash", "cpp", "python" ]
toc = true
posts_navigation = true
progressively = true
github = "wangyongcong"
email = "wangyongcong@gmail.com"

[[menu.primary]]
identifier = "EN"
name = "English"
url = "/"
weight = 10

[[menu.primary]]
identifier = "CN"
name = "中文"
url = "/CN/"
weight = 20

[[menu.footer]]
identifier = "tags"
name = "Tags"
url = "/tags/"
weight = 50
